#!/bin/bash
# From https://github.com/davidecavestro/mariadb-docker-armhf/blob/756c3f31a1/hooks/pre_build
# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
docker run --rm --privileged multiarch/qemu-user-static:register --reset
