---
name: Deploy image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*'

env:
  REGISTRY: ghcr.io
  GHCR_IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/resiliosync-multiarch

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # If this workflow was triggered by a tag it's a "release", extract the version
      - if: github.ref_type == 'tag'
        name: Extract release from Dockerfile
        id: release
        run: echo release=$(grep '^ARG RELEASE=' Dockerfile | cut -d\" -f2) >> "$GITHUB_OUTPUT"

      - name: Extract repository metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}
            docker.io/${{ env.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag
            type=ref,event=branch,suffix=-branch

      # Add latest and version number if it's a release
      - if: github.ref_type == 'tag'
        name: Extract additional tags for Docker
        id: additional_tags
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}
            docker.io/${{ env.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.release.outputs.release }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.additional_tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/386,linux/arm/v5,linux/arm/v7,linux/arm64/v8

